https://github.com/BuzzKiLL3/Transfer.git

python camera3.py 
Traceback (most recent call last):
  File "/home/imt/src/camera3.py", line 10, in <module>
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
                                         ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'data'


pip install opencv-contrib-python

sudo apt update
sudo apt upgrade

sudo apt install -y build-essential cmake pkg-config
sudo apt install -y libjpeg-dev libtiff-dev libpng-dev
sudo apt install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt install -y libxvidcore-dev libx264-dev
sudo apt install -y libfontconfig1-dev libcairo2-dev
sudo apt install -y libgdk-pixbuf2.0-dev libpango1.0-dev
sudo apt install -y libgtk2.0-dev libgtk-3-dev
sudo apt install -y libatlas-base-dev gfortran
sudo apt install -y python3-dev python3-numpy

cd ~/Downloads
wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.x.zip

cd ~/opencv
mkdir build
cd build


cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
      -D ENABLE_NEON=ON \
      -D ENABLE_VFPV3=ON \
      -D BUILD_TESTS=OFF \
      -D OPENCV_ENABLE_NONFREE=ON \
      -D INSTALL_PYTHON_EXAMPLES=OFF \cd ~/opencv
mkdir build
cd build
bash: cd: /home/imt/opencv: No such file or directory
mkdir: cannot create directory ‘build’: File exists

      -D BUILD_EXAMPLES=OFF ..


make -j4  # Adjust '4' based on your Raspberry Pi model’s CPU cores


sudo make install
sudo ldconfig


check
python3 -c "import cv2; print('face' in dir(cv2))"


cd ~/opencv
mkdir build
cd buildpython camera3.py 
Traceback (most recent call last):
  File "/home/imt/src/camera3.py", line 10, in <module>
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
                                         ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'data'

python camera3.py 
Traceback (most recent call last):
  File "/home/imt/src/camera3.py", line 10, in <module>
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
                                         ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'data'
https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xmls

python camera3.py 
Training completed with your image.
[ WARN:0@3.855] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0@3.856] global ./modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@3.856] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created


imt@raspberrypi:~/src $ python camera3.py 
Training completed with your image.
imt@raspberrypi:~/src $ python camera3.py 
Training completed with your image.



sudo apt remove --purge -y build-essential cmake pkg-config libjpeg-dev libtiff-dev libpng-dev \
libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev \
libfontconfig1-dev libcairo2-dev libgdk-pixbuf2.0-dev libpango1.0-dev \
libgtk2.0-dev libgtk-3-dev libatlas-base-dev gfortran python3-dev python3-numpy

sudo apt autoremove -y



----------------------------------------------

sudo apt-get update && sudo apt-get upgrade

sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev


	
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev 
sudo apt-get install libxvidcore-dev libx264-dev


    sudo apt-get install libgtk2.0-dev


sudo apt-get install libatlas-base-dev gfortran


pip install numpy

 	
apt list python*opencv*

sudo apt install python3-opencv

apt show python3-opencv


imt@raspberrypi:~/src $ /bin/python /home/imt/src/final1.py
Traceback (most recent call last):
  File "/home/imt/src/final1.py", line 16, in <module>
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
                                         ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'data'


imt@raspberrypi:~/src $ /bin/python /home/imt/src/camera3.py
Traceback (most recent call last):
  File "/home/imt/src/camera3.py", line 5, in <module>
    import picamera2.array
ModuleNotFoundError: No module named 'picamera2.array'

imt@raspberrypi:~/src $ /bin/python /home/imt/src/camera3.py
[0:46:41.558638522] [5319]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:46:41.592345167] [5334]  WARN RPiSdn sdn.cpp:40 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[0:46:41.594437707] [5334]  WARN RPI vc4.cpp:393 Mismatch between Unicam and CamHelper for embedded data usage!
[0:46:41.595203627] [5334]  INFO RPI vc4.cpp:447 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media0 and ISP device /dev/media1
[0:46:41.595312182] [5334]  INFO RPI pipeline_base.cpp:1126 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
Traceback (most recent call last):
  File "/home/imt/src/camera3.py", line 7, in <module>
    picam2.configure(picam2.preview_configuration(main={"format": 'BGR', "size": (640, 480)}))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'CameraConfiguration' object is not callable


imt@raspberrypi:~/src $ /bin/python /home/imt/src/camera3.py
[0:48:10.374398698] [5370]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[0:48:10.409778888] [5388]  WARN RPiSdn sdn.cpp:40 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[0:48:10.411665206] [5388]  WARN RPI vc4.cpp:393 Mismatch between Unicam and CamHelper for embedded data usage!
[0:48:10.412496273] [5388]  INFO RPI vc4.cpp:447 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media0 and ISP device /dev/media1
[0:48:10.412647901] [5388]  INFO RPI pipeline_base.cpp:1126 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
Traceback (most recent call last):
  File "/home/imt/src/camera3.py", line 9, in <module>
    preview_config = picam2.preview_configuration(main={"format": 'BGR', "size": (640, 480)})
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'CameraConfiguration' object is not callable


python main.py 
Training completed with your image.
Error: Unable to read from camera.


imt@raspberrypi:~/src $ /bin/python /home/imt/src/final/temp.py
[ERROR:0@0.845] global ./modules/core/src/persistence.cpp (505) open Can't open file: 'haarcascade_frontalface_default.xml' in read mode
ERROR:OpenCV(4.6.0) ./modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

To fix this, look at: 
        File: /home/imt/src/final/temp.py
        Line: 22
To see the full stack trace, type this terminal command:
         nano /tmp/tmph1607d0z
*************************************************

in nano i have this 
 File "/home/imt/src/final/temp.py", line 80, in <module>
    start_camera()
  File "/home/imt/src/final/temp.py", line 35, in start_camera
    with Camera() as cam:


ret, frame = cap.read()  # Read a frame from the camera




 63.839303] vc4-drm gpu: swiotlb buffer is full (sz: 417792 bytes), total 32768 (slots), used 1472 (slots)
[   88.462130] unicam fe801000.csi: Wrong width or height 3840x2160 (remote pad set to 3280x2464)
[   88.462154] unicam fe801000.csi: Failed to start media pipeline: -22
[   88.920370] unicam fe801000.csi: Wrong width or height 640x480 (remote pad set to 3280x2464)
[   88.920411] unicam fe801000.csi: Failed to start media pipeline: -22
[  181.906274] swiotlb_tbl_map_single: 8 callbacks suppressed
[  181.906288] vc4-drm gpu: swiotlb buffer is full (sz: 2256896 bytes), total 32768 (slots), used 50 (slots)
[  181.908301] vc4-drm gpu: swiotlb buffer is full (sz: 2256896 bytes), total 32768 (slots), used 50 (slots)
[  181.918871] vc4-drm gpu: swiotlb buffer is full (sz: 2359296 bytes), total 32768 (slots), used 0 (slots)
[  181.921972] vc4-drm gpu: swiotlb buffer is full (sz: 2359296 bytes), total 32768 (slots), used 0 (slots)
[  246.570860] v3d fec00000.v3d: MMU error from client CLE (4) at 0x11181000, pte invalid
[  246.658691] vc4-drm gpu: swiotlb buffer is full (sz: 532480 bytes), total 32768 (slots), used 60 (slots)
[  246.661580] vc4-drm gpu: swiotlb buffer is full (sz: 532480 bytes), total 32768 (slots), used 60 (slots)
[  246.699575] vc4-drm gpu: swiotlb buffer is full (sz: 655360 bytes), total 32768 (slots), used 0 (slots)
[  246.701853] vc4-drm gpu: swiotlb buffer is full (sz: 655360 bytes), total 32768 (slots), used 0 (slots)
[  246.704686] vc4-drm gpu: swiotlb buffer is full (sz: 655360 bytes), total 32768 (slots), used 0 (slots)
[  246.716285] vc4-drm gpu: swiotlb buffer is full (sz: 655360 bytes), total 32768 (slots), used 0 (slots)
imt@raspberrypi:~ $ 

sudo python3 camerafinal.py 
[ WARN:0@0.405] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0@0.406] global ./modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@0.406] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
Traceback (most recent call last):
  File "/home/imt/src/car/camerafinal.py", line 16, in <module>
    motor_process = subprocess.Popen(["/home/imt/src/car/motorfinal.c"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/imt/src/car/motorfinal.c'


gcc motorfinal.c -o motorfinal
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1c): undefined reference to `main'
/usr/bin/ld: (.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

udo ./motorfinal
ERROR: GPIOSetDir() -> fopen(/sys/class/gpio/gpio17/direction,..)
       error code 2 (No such file or directory)
ERROR: Failed to set direction for GPIO pins


/motor-start
ERROR: GPIOSetDir() -> fopen(/sys/class/gpio/gpio20/direction,..)
       error code 2 (No such file or directory)
ERROR: Failed to set direction for GPIO pins


sudo echo 17 > /sys/class/gpio/gpio17
bash: /sys/class/gpio/gpio17: Permission denied


echo 17 | sudo tee /sys/class/gpio/export
17
tee: /sys/class/gpio/export: Invalid argument


sudo python3 camerafinal.py 
Traceback (most recent call last):
  File "/home/imt/src/car/camerafinal.py", line 16, in <module>
    motor_process = subprocess.Popen(["/home/imt/src/car/motorfinal.c"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/imt/src/car/motorfinal.c'


/bin/python /home/imt/src/final/testcam11.py
[ERROR:0@0.246] global ./modules/core/src/persistence.cpp (505) open Can't open file: 'haarcascade_frontalface_default.xml' in read mode
[1:00:38.460360340] [3735]  INFO Camera camera_manager.cpp:325 libcamera v0.3.2+27-7330f29b
[1:00:38.534408094] [3738]  WARN RPiSdn sdn.cpp:40 Using legacy SDN tuning - please consider moving SDN inside rpi.denoise
[1:00:38.542287324] [3738]  WARN RPI vc4.cpp:393 Mismatch between Unicam and CamHelper for embedded data usage!
[1:00:38.545543779] [3738]  INFO RPI vc4.cpp:447 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media1 and ISP device /dev/media0
[1:00:38.545895035] [3738]  INFO RPI pipeline_base.cpp:1126 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
Mode selection for 1640:1230:12:P
    SRGGB10_CSI2P,640x480/0 - Score: 4500
    SRGGB10_CSI2P,1640x1232/0 - Score: 1006.99
    SRGGB10_CSI2P,1920x1080/0 - Score: 1536.67
    SRGGB10_CSI2P,3280x2464/0 - Score: 1724.99
    SRGGB8,640x480/0 - Score: 5500
    SRGGB8,1640x1232/0 - Score: 2006.99
    SRGGB8,1920x1080/0 - Score: 2536.67
    SRGGB8,3280x2464/0 - Score: 2724.99
[1:00:38.550256906] [3735]  INFO Camera camera.cpp:1197 configuring streams: (0) 1640x1230-YUV420 (1) 1640x1232-SBGGR10_CSI2P
[1:00:38.553417880] [3738]  INFO RPI vc4.cpp:622 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 1640x1232-SBGGR10_1X10 - Selected unicam format: 1640x1232-pBAA
Mode selection for 640:480:12:P
    SRGGB10_CSI2P,640x480/0 - Score: 1000
    SRGGB10_CSI2P,1640x1232/0 - Score: 1444.49
    SRGGB10_CSI2P,1920x1080/0 - Score: 1636.67
    SRGGB10_CSI2P,3280x2464/0 - Score: 2162.49
    SRGGB8,640x480/0 - Score: 2000
    SRGGB8,1640x1232/0 - Score: 2444.49
    SRGGB8,1920x1080/0 - Score: 2636.67
    SRGGB8,3280x2464/0 - Score: 3162.49
[1:00:38.964870398] [3735]  INFO Camera camera.cpp:1197 configuring streams: (0) 640x480-YUV420 (1) 640x480-SBGGR10_CSI2P
[1:00:38.968317388] [3738]  INFO RPI vc4.cpp:622 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 640x480-SBGGR10_1X10 - Selected unicam format: 640x480-pBAA
Still capture image received
Traceback (most recent call last):
  File "/home/imt/src/final/testcam11.py", line 50, in <module>
    main()
  File "/home/imt/src/final/testcam11.py", line 35, in main
    frame_with_faces, face_count = detect_faces(frame)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/home/imt/src/final/testcam11.py", line 23, in detect_faces
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.6.0) ./modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

Halting: reached timeout of 5000 milliseconds.
